name: Daily LinkedIn Jobs Scraper

on:
  schedule:
    - cron: "0 3 * * *"   # Runs daily at 3:00 UTC
  workflow_dispatch:      # Optional manual run

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python linkedin_jobs_scrapper.py

      - name: Commit & Push results
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add data/
          git commit -m "Daily job scrape: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
