name: LinkedIn Job Scraper

on:
  schedule:
    - cron: "30 2 * * *"  # Adjust for desired time
  workflow_dispatch:

permissions:
  contents: write  # Allow workflow to push to the repo

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: python linkedin_jobs_scrapper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Daily job scrape: $(date +'%Y-%m-%d')" || exit 0
          git push
